export function setupCompactUI(){
 const image=document.getElementById('line-upload'),model=document.getElementById('upload'),row=document.createElement('div');row.className='compact-upload-row';document.querySelector('.upload-group').before(row);row.append(image,model);image.textContent='＋ 图片';model.textContent='＋ 模型';image.setAttribute('aria-label','上传二维图片');model.setAttribute('aria-label','上传三维模型 GLB');
 const count=document.getElementById('count').closest('.field'),size=document.getElementById('size-m').closest('.field'),pair=document.createElement('div');pair.className='compact-pair';count.before(pair);pair.append(count,size);
 const media=document.querySelector('.media-section');if(media){const details=document.createElement('details');details.className='compact-details';const summary=document.createElement('summary');summary.textContent='背景与导出';media.before(details);details.append(summary,media);const heading=media.querySelector('h2');if(heading)heading.hidden=true;}
 const tooltip=document.createElement('div');tooltip.className='compact-tooltip';tooltip.id='compact-help';tooltip.setAttribute('role','tooltip');tooltip.hidden=true;document.body.append(tooltip);let owner=null,pinned=false;
 function close(){tooltip.hidden=true;if(owner)owner.setAttribute('aria-expanded','false');owner=null;pinned=false;}
 function show(button,p){if(owner&&owner!==button)owner.setAttribute('aria-expanded','false');owner=button;tooltip.textContent=p.textContent;tooltip.hidden=false;button.setAttribute('aria-expanded','true');const r=button.getBoundingClientRect(),w=tooltip.offsetWidth,h=tooltip.offsetHeight;tooltip.style.left=Math.max(8,Math.min(innerWidth-w-8,r.left))+'px';tooltip.style.top=Math.max(8,r.bottom+h+12<innerHeight?r.bottom+6:r.top-h-6)+'px';}
 const hints=[...document.querySelectorAll('p.hint:not([id]),#preview-hint,#growth-origin-hint')].filter(p=>!p.closest('#line-draft'));
 hints.forEach(p=>{const button=document.createElement('button');button.type='button';button.className='help-dot';button.textContent='ⓘ';button.setAttribute('aria-label','查看操作说明');button.setAttribute('aria-describedby',tooltip.id);button.setAttribute('aria-expanded','false');p.before(button);p.hidden=true;button.addEventListener('mouseenter',()=>{if(!pinned)show(button,p);});button.addEventListener('mouseleave',()=>{if(!pinned)close();});button.addEventListener('focus',()=>show(button,p));button.addEventListener('blur',()=>{if(!pinned)close();});button.addEventListener('click',()=>{if(owner===button&&pinned)close();else{show(button,p);pinned=true;}});});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});document.addEventListener('pointerdown',e=>{if(owner&&!owner.contains(e.target)&&!tooltip.contains(e.target))close();});window.addEventListener('resize',close);document.addEventListener('scroll',close,true);
}
