import {MAX_SCENES,TRANSITIONS,connectionRange,stageDuration,scenesFor,sequence,segmentAt,sceneMotion,matchPoints,prepareTransition,transitionFrame} from './animation/storyboard.mjs';
import {sourceColors} from './geometry/strokes.mjs';
import {depthFactors} from './geometry/audience.mjs';
import {totalDuration,motionFor} from './animation/motion.mjs';
const linear=v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4;
export function setupStoryboard({store,view,active,source,message,pause,restore,blocked}){
 const root=document.createElement('section');root.className='storyboard';root.innerHTML='<div class="story-heading"><strong>分镜编排 <span id="scene-count"></span></strong><span id="sequence-duration"></span><button id="scene-add" data-edit>＋ 当前素材加入分镜</button><button id="scene-copy" data-edit>复制分镜</button><button id="scene-remove" data-edit>移除分镜</button><button id="sequence-play" data-edit>播放全片</button><button id="sequence-stop">停止全片</button></div><div id="scene-cards" class="scene-cards"></div><div id="transition-editor" hidden><label>转场 <select id="transition-effect" data-edit></select></label><label><span id="transition-time-label">换位时长</span> <input id="transition-duration" data-edit type="number" min="0.2" max="30" step="0.1"> 秒</label><button id="transition-play" data-edit>预览这次转场</button><span id="connection-description"></span></div><p class="hint" id="story-hint">将素材加入分镜；点击卡片切换，拖动排序。缩略图为正面静态布点示意。</p>';
 document.querySelector('.playback').after(root);const $=id=>root.querySelector('#'+id);
 for(const [value,policy] of Object.entries(TRANSITIONS)){const option=document.createElement('option');option.value=value;option.textContent=policy.label;$('transition-effect').append(option);}
 let selected=null,link=null,run=null,drag=null;const thumbs=new WeakMap(),pairs=new WeakMap();
 function commit(label,fn){if(blocked()||run)return;try{store.commit(label,fn);}catch(e){message(e.message,true);}}
 function rgb(f){let colors=f.points.uv&&source(f)?.raster&&f.colorMode!=='uniform'?sourceColors(source(f).raster,f.points.uv,f.generation):null;if(!colors){const c=[1,3,5].map(i=>linear(parseInt(f.color.slice(i,i+2),16)/255));colors=new Float32Array(f.points.positions.length);for(let i=0;i<colors.length;i++)colors[i]=c[i%3];}const depth=depthFactors(f.points.positions,(f.audienceSource||f.points).positions,f.audience);for(let i=0;i<colors.length;i++)colors[i]*=depth[Math.floor(i/3)];return colors;}
 function world(f){return Float32Array.from(f.points.positions,(v,i)=>v+f.transform.position[i%3]);}
 function thumb(canvas,f){const ctx=canvas.getContext('2d');let cached=thumbs.get(f);if(cached){ctx.drawImage(cached,0,0);return;}ctx.fillStyle='#030910';ctx.fillRect(0,0,160,90);const p=f.points.positions,c=rgb(f);let loX=Infinity,hiX=-Infinity,loY=Infinity,hiY=-Infinity;for(let i=0;i<p.length;i+=3){loX=Math.min(loX,p[i]);hiX=Math.max(hiX,p[i]);loY=Math.min(loY,p[i+1]);hiY=Math.max(hiY,p[i+1]);}const scale=74/Math.max(hiY-loY,(hiX-loX)*74/144,1);const srgb=v=>Math.round(255*(v<=.0031308?v*12.92:1.055*v**(1/2.4)-.055));for(let i=0;i<p.length;i+=3){ctx.fillStyle=`rgb(${srgb(c[i])},${srgb(c[i+1])},${srgb(c[i+2])})`;ctx.fillRect(80+(p[i]-(hiX+loX)/2)*scale,45-(p[i+1]-(hiY+loY)/2)*scale,1.5,1.5);}const saved=document.createElement('canvas');saved.width=160;saved.height=90;saved.getContext('2d').drawImage(canvas,0,0);thumbs.set(f,saved);}
 function sync(){const scenes=scenesFor(store.state);if(!scenes.some(s=>s.id===selected&&s.formationId===store.state.activeId))selected=scenes.find(s=>s.formationId===store.state.activeId)?.id||null;if(!scenes.some(s=>s.id===link))link=null;$('scene-count').textContent=`${scenes.length} / ${MAX_SCENES} 幕`;$('sequence-duration').textContent=`全片 ${sequence(store.state).duration.toFixed(1)} 秒`;$('scene-cards').replaceChildren();
 scenes.forEach((s,i)=>{const f=store.state.formations.find(f=>f.id===s.formationId),card=document.createElement('button');card.className='scene-card';card.dataset.scene=s.id;card.setAttribute('aria-pressed',String(s.id===selected));card.draggable=!blocked()&&!run;card.disabled=blocked()||!!run;const canvas=document.createElement('canvas');canvas.width=160;canvas.height=90;thumb(canvas,f);const text=document.createElement('span');text.textContent=`${i+1}. ${f.name} · ${totalDuration(motionFor(f)).toFixed(1)}秒`;card.append(canvas,text);card.onclick=()=>{selected=s.id;link=null;pause();store.select(f.id);restore();sync();};card.ondragstart=()=>{drag=s.id;};card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();if(!drag||drag===s.id)return;commit('排序分镜',p=>{const list=[...scenesFor(p)],from=list.findIndex(x=>x.id===drag),to=list.findIndex(x=>x.id===s.id);if(from<0||to<0)return p;list.splice(to,0,list.splice(from,1)[0]);return {...p,storyboard:list};});drag=null;};$('scene-cards').append(card);
 if(i<scenes.length-1){const b=document.createElement('button');b.className='scene-link';b.disabled=blocked()||!!run;b.textContent=`${TRANSITIONS[s.transition.effect].label} · ${s.transition.duration}秒`;b.onclick=()=>{link=s.id;sync();};$('scene-cards').append(b);}});
 const s=scenes.find(s=>s.id===link),hasNext=s&&scenes.indexOf(s)<scenes.length-1;$('transition-editor').hidden=!hasNext;if(hasNext){$('transition-effect').value=s.transition.effect;$('transition-duration').value=s.transition.duration;
 const next=store.state.formations.find(f=>f.id===scenes[scenes.indexOf(s)+1].formationId),prev=store.state.formations.find(f=>f.id===s.formationId),exit=motionFor(prev).exit,enter=motionFor(next).enter;
 const label=(stage,effect)=>document.querySelector('#'+stage+'-effect option[value="'+effect+'"]')?.textContent||effect;
 $('transition-time-label').textContent=s.transition.effect==='dark'?'暗场换位时长':'连续变形时长';
 $('connection-description').textContent=s.transition.effect==='dark'?`前幕：${label('exit',exit.effect)} ${stageDuration(motionFor(prev),'exit')} 秒 → 暗场换位 ${s.transition.duration} 秒 → 后幕：${label('enter',enter.effect)} ${stageDuration(motionFor(next),'enter')} 秒。保留出入场；预览包含整个连接。`:'本连接替代前幕退场与后幕入场；持续动态时长不变，单幕预览不变。';}
 $('scene-add').disabled=blocked()||!!run||!active()||scenes.length>=MAX_SCENES;$('scene-copy').disabled=blocked()||!!run||!selected||scenes.length>=MAX_SCENES;$('scene-remove').disabled=blocked()||!!run||!selected;$('sequence-play').disabled=blocked()||!!run||!scenes.length;$('sequence-stop').disabled=!run;for(const id of ['transition-effect','transition-duration','transition-play'])$(id).disabled=blocked()||!!run;
 }
 $('scene-add').onclick=()=>{const f=active();if(!f)return;const id=crypto.randomUUID();selected=id;commit('添加分镜',p=>({...p,storyboard:[...scenesFor(p),{id,formationId:f.id,transition:{effect:'dark',duration:2}}]}));};
 $('scene-copy').onclick=()=>commit('复制分镜',p=>{const list=[...scenesFor(p)],i=list.findIndex(s=>s.id===selected);if(i<0)return p;const f=p.formations.find(f=>f.id===list[i].formationId),copy=structuredClone(f);copy.id=crypto.randomUUID();copy.name+=' 副本';copy.revision=0;const id=crypto.randomUUID();list.splice(i+1,0,{...structuredClone(list[i]),id,formationId:copy.id});selected=id;return {...p,formations:[...p.formations,copy],activeId:copy.id,storyboard:list};});
 $('scene-remove').onclick=()=>commit('移除分镜',p=>({...p,storyboard:scenesFor(p).filter(s=>s.id!==selected)}));
 function changeTransition(){commit('修改转场',p=>({...p,storyboard:scenesFor(p).map(s=>s.id===link?{...s,transition:{effect:$('transition-effect').value,duration:Number($('transition-duration').value)}}:s)}));}
 $('transition-effect').onchange=changeTransition;$('transition-duration').onchange=changeTransition;
 function stop(){if(!run)return;run=null;restore();sync();}
 function start(onlyLink=false){if(blocked()||run)return;const plan=sequence(store.state);if(!plan.segments.length)return;try{pause();const prepared=new Map();for(const s of plan.segments)if(s.kind==='transition'){let targets=pairs.get(s.f);if(!targets){targets=new WeakMap();pairs.set(s.f,targets);}let q=targets.get(s.to);if(!q){const a=world(s.f),b=world(s.to);q=prepareTransition(a,b,rgb(s.f),rgb(s.to));targets.set(s.to,q);}prepared.set(s.scene.id,q);}const seg=onlyLink?plan.segments.find(s=>s.kind==='transition'&&s.scene.id===link):null;if(onlyLink&&!seg)return;const range=seg?connectionRange(seg):{start:0,end:plan.duration};run={plan,prepared,time:range.start,end:range.end,last:null};sync();message('全片预览中；可拖动检查视角，点击停止返回编辑。');}catch(e){message(e.message,true);stop();}}
 $('sequence-play').onclick=()=>start();$('transition-play').onclick=()=>start(true);$('sequence-stop').onclick=stop;
 store.subscribe(()=>{if(run)stop();sync();});sync();
 return {get running(){return !!run;},sync,stop,tick(dt){if(!run)return false;const s=segmentAt(run.plan,run.time);if(!s){stop();return false;}if(s.kind==='scene'){const f={...s.f,motion:s.motion};view.setFormation(f,source(s.f));view.draw(s.t,'animation');}else{const q=run.prepared.get(s.scene.id);transitionFrame(q.a,q.b,q.ca,q.cb,q.map,s.t,s.scene.transition.effect,q.out,q.colors);view.transition(q.out,q.colors);}document.getElementById('phase').textContent=s.kind==='scene'?`全片 · 第 ${s.index+1} 幕`:`全片 · 第 ${s.index+1} → ${s.index+2} 幕转场`;for(const card of root.querySelectorAll('[data-scene]'))card.classList.toggle('playing',card.dataset.scene===s.scene.id);view.render();if(run.time>=run.end){stop();return true;}run.time=Math.min(run.end,run.time+dt);return true;}};
}
