import test from 'node:test';import assert from 'node:assert/strict';
import {sequence,segmentAt,sceneMotion,matchPoints,transitionFrame,validateStoryboard,connectionRange} from '../animation/storyboard.mjs';
import {createProject,createFormation,ProjectStore} from '../project/model.mjs';import {serializeProject,parseProject} from '../project/persistence.mjs';import {totalDuration} from '../animation/motion.mjs';
function project(){const p=createProject(),a=createFormation('A',new Float32Array([0,0,0,1,0,0]),{kind:'preset',preset:'sphere'}),b=createFormation('B',new Float32Array([3,0,0,2,0,0]),{kind:'preset',preset:'sphere'});p.formations=[a,b];p.activeId=a.id;p.fleet.count=2;p.storyboard=[{id:'one',formationId:a.id,transition:{effect:'dark',duration:2}},{id:'two',formationId:b.id,transition:{effect:'morph',duration:2}}];return p;}
test('two scenes total 12 seconds; transition boundary resolves to next scene',()=>{const p=project(),s=sequence(p);assert.equal(s.duration,12);assert.equal(segmentAt(s,5).kind,'transition');assert.equal(segmentAt(s,7).f.name,'B');assert.equal(segmentAt(s,12).t,1);for(let i=0;i<2;i++){const m=sceneMotion(p.formations[i],i?'dark':null,i?null:'dark');assert.equal(totalDuration(m),5);assert.notEqual(i?m.enter.effect:m.exit.effect,'skip');}});
test('spatial matching is bijective and transition keeps point count and exact endpoints',()=>{const p=project(),a=p.formations[0].points.positions,b=p.formations[1].points.positions,map=matchPoints(a,b),c=new Float32Array([1,0,0,0,1,0]),d=new Float32Array([0,0,1,1,1,1]),out=new Float32Array(6),colors=new Float32Array(6);assert.equal(new Set(map).size,2);for(const effect of ['dark','morph']){transitionFrame(a,b,c,d,map,0,effect,out,colors);assert.deepEqual(out,a);assert.deepEqual(colors,effect==='dark'?new Float32Array(c.length):c);transitionFrame(a,b,c,d,map,1,effect,out,colors);for(let i=0;i<2;i++)assert.deepEqual(out.slice(i*3,i*3+3),b.slice(map[i]*3,map[i]*3+3));}transitionFrame(a,b,c,d,map,.5,'dark',out,colors);assert.ok(colors.every(v=>v===0));assert.throws(()=>matchPoints(a,new Float32Array(3)));});
test('scene limit, duration and reference validation; save and undo preserve sequence',()=>{const p=project();assert.deepEqual(parseProject(serializeProject(p)).storyboard,p.storyboard);const store=new ProjectStore(p);store.commit('reverse',p=>({...p,storyboard:[...p.storyboard].reverse()}));assert.equal(store.state.storyboard[0].id,'two');store.undo();assert.equal(store.state.storyboard[0].id,'one');const twelve={...p,storyboard:Array.from({length:12},(_,i)=>({...p.storyboard[0],id:String(i)}))};validateStoryboard(twelve);assert.throws(()=>validateStoryboard({...twelve,storyboard:[...twelve.storyboard,{...p.storyboard[0],id:'13'}]}));assert.throws(()=>validateStoryboard({...p,storyboard:[{...p.storyboard[0],formationId:'missing'}]}));assert.throws(()=>validateStoryboard({...p,storyboard:[{...p.storyboard[0],transition:{effect:'dark',duration:NaN}}]}));});

test('mixed connections suppress only morph-facing edges without stretching hold duration',()=>{const p=project(),c=createFormation('C',new Float32Array([0,0,0,1,1,0]),{kind:'preset',preset:'sphere'});p.formations.push(c);p.storyboard.push({id:'three',formationId:c.id,transition:{effect:'dark',duration:2}});const plan=sequence(p),scenes=plan.segments.filter(s=>s.kind==='scene');assert.equal(plan.duration,16);assert.equal(scenes[0].duration,5);assert.equal(scenes[1].duration,3.5);assert.equal(scenes[2].duration,3.5);assert.notEqual(scenes[1].motion.enter.effect,'skip');assert.equal(scenes[1].motion.exit.effect,'skip');assert.equal(scenes[1].motion.hold.duration,2);assert.equal(p.formations[1].motion.exit.effect,'fade');const links=plan.segments.filter(s=>s.kind==='transition');assert.deepEqual(connectionRange(links[0]),{start:3.5,end:8.5});assert.deepEqual(connectionRange(links[1]),{start:10.5,end:12.5});});
test('dark relocation is fully unlit; skipped edges add no hidden duration',()=>{const p=project();p.formations[0].motion.exit.effect='skip';p.formations[1].motion.enter.effect='skip';const plan=sequence(p),link=plan.segments.find(s=>s.kind==='transition');assert.equal(plan.duration,9);assert.deepEqual(connectionRange(link),{start:3.5,end:5.5});const a=new Float32Array([0,0,0]),b=new Float32Array([4,0,0]),out=new Float32Array(3),colors=new Float32Array(3);for(const t of [0,.25,.5,.75,1]){transitionFrame(a,b,b,b,new Uint32Array([0]),t,'dark',out,colors);assert.ok(colors.every(v=>v===0));assert.ok(out[0]>=0&&out[0]<=4);}assert.equal(out[0],4);});
