import test from 'node:test';import assert from 'node:assert/strict';
import {strokeRouting} from '../animation/stroke-routing.mjs';
import {sampleMotion,defaultMotion,validateMotion} from '../animation/motion.mjs';
import {createProject,createFormation,id} from '../project/model.mjs';import {serializeProject,parseProject} from '../project/persistence.mjs';
const points={positions:new Float32Array([-2,0,0,-1,0,0,0,0,0,1,0,0,2,0,0]),strokeIds:new Float32Array(5)};
test('left/right/center routing travels along a stroke and caches repeat sampling',()=>{const left=strokeRouting(points,'left'),right=strokeRouting(points,'right'),center=strokeRouting(points,'center');assert.deepEqual([...left.order],[0,.25,.5,.75,1]);assert.deepEqual([...right.order],[1,.75,.5,.25,0]);assert.deepEqual([...center.order],[1,.5,0,.5,1]);assert.equal(left,strokeRouting(points,'left'));});
test('routing follows a bent stroke, reaches disconnected components, no coordinate mutation',()=>{const p={positions:new Float32Array([0,0,0,0,4,0,1,4,0,1,0,0,8,0,0,9,0,0]),strokeIds:new Float32Array([0,0,0,0,1,1])},before=p.positions.slice(),r=strokeRouting(p,'left');assert.ok(r.order[3]>r.order[2]);assert.ok(r.order.every(Number.isFinite));assert.equal(Math.max(...r.order),1);assert.deepEqual(p.positions,before);});
test('stroke relay lights groups together; local breathing leaves other strokes stable',()=>{const base=new Float32Array([0,0,0,1,0,0,2,0,0,3,0,0]),routing={ids:new Float32Array([0,0,1,1]),order:new Float32Array([0,.3,.6,1])},bounds={min:[0,0,0],size:[3,0,0]},out=new Float32Array(12),light=new Float32Array(4),m=defaultMotion();m.enter={effect:'stroke-relay',duration:2};m.hold.effect='skip';m.exit.effect='skip';sampleMotion(base,m,.25,out,light,bounds,true,routing);assert.equal(light[0],light[1]);assert.ok(light[0]>light[2]);sampleMotion(base,m,1,out,light,bounds,true,routing);assert.ok(light.every(v=>v===1));m.enter.effect='skip';m.hold={effect:'local-breathe',duration:2};sampleMotion(base,m,.5,out,light,bounds,true,routing);assert.ok(light[0]<.31);assert.equal(light[2],1);assert.deepEqual(out,base);for(const t of [0,1]){sampleMotion(base,m,t,out,light,bounds,true,routing);assert.ok(light.every(v=>v===1));}});
test('new stroke metadata and origin survive project roundtrip; invalid origin rejected',()=>{const p=createProject(),a={id:id(),name:'a',type:'raster',mime:'image/png',original:new Uint8Array([1]),raster:{width:1,height:1,data:new Uint8ClampedArray([255,255,255,255])}},f=createFormation('line',points.positions,{kind:'lineart',sampling:'strokes',mode:'light',threshold:100,sizeM:22},a.id);f.points.strokeIds=points.strokeIds;f.motion.enter={effect:'grow',duration:1.5,origin:'right'};p.assets=[a];p.formations=[f];p.activeId=f.id;p.fleet.count=5;const q=parseProject(serializeProject(p));assert.deepEqual(q.formations[0].points.strokeIds,points.strokeIds);assert.equal(q.formations[0].motion.enter.origin,'right');f.motion.enter.origin='unknown';assert.throws(()=>validateMotion(f.motion));});
